version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build:
      context: .
    container_name: movie-rating-app
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    container_name: movie-rating-nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - web
  
  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  static:
